### ISSUE TITLE
Could please share the trained model weights?

### ISSUE THREAD

**Issue by feixyz10** [eth-siplab/BeliefPPG#1]
It will be very helpful and we will be extremely grateful if you can share the trained model weights.

**Comment by valebi** [comment]
Sure! There were quite a few experiments - why don't you drop me an email with a sentence about what exactly you need (and what for)? :) 
My ETH email address is username[at]student.ethz.ch, where the username is 'bieriv'.

**Comment by paulstreli** [comment]
@feixyz10 We added a pre-trained model to our repository. You can also install BeliefPPG via pip if you intend to use it for inference.
